version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/application
    steps:
      - checkout
      - run:
          name: Update npm
          command: "sudo npm install -g npm@latest"
      - run:
          name: Install npm wee
          command: npm install
  build_and_deploy:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/application
    steps:
      - run:
          name: Deploy
          command: |
            npm run build && npm run deploy
workflows:
  version: 2.1
  build:
    jobs:
      - setup
      - build_and_deploy:
          requires:
            - setup
          filters:
            branches:
              only:
                - master